export const newsTypeData = [
  {
    icon: require('images/news/new-w.svg'),
    title: '网格化搜捕',
    desc: '网格化搜捕任务简单介绍',
    time: '8分钟前',
    num: 10,
  },
  {
    icon: require('images/news/new-x.svg'),
    title: '训练计划',
    desc: '训练计划简单介绍',
    time: '8分钟前',
    num: 0,
  },
  {
    icon: require('images/news/new-r.svg'),
    title: '日常巡逻',
    desc: '日常巡逻简单介绍',
    time: '8分钟前',
    num: 100,
  },
  {
    icon: require('images/news/new-jing.svg'),
    title: '紧急调配',
    desc: '紧急调配简单介绍',
    time: '8分钟前',
    num: 3,
  },
  {
    icon: require('images/news/new-jia.svg'),
    title: '假期管理',
    desc: '假期管理简单介绍',
    time: '8分钟前',
    num: 10,
  },
  {
    icon: require('images/news/new-z.svg'),
    title: '值班提醒',
    desc: '值班提醒简单介绍',
    time: '8分钟前',
    num: 1,
  },
];
export const newsListNoTypeData = [
  {
    icon: require('images/news/new-w.svg'),
    title: '塘朗山网格化搜谱',
    content: '在塘朗山附近组织山地野…',
    startTime: '2020-01-24 10:00',
    pusher: '王海青1',
    status: 1,
  },
  {
    icon: require('images/news/new-w.svg'),
    title: '塘朗山网格化搜谱',
    content: '在塘朗山附近组织山地野…',
    startTime: '2020-01-24 10:00',
    pusher: '王海青2',
    status: 0,
  },
  {
    icon: require('images/news/new-w.svg'),
    title: '塘朗山网格化搜谱',
    content: '在塘朗山附近组织山地野…',
    startTime: '2020-01-24 10:00',
    pusher: '王海青3',
    status: 0,
  },
  {
    icon: require('images/news/new-w.svg'),
    title: '塘朗山网格化搜谱',
    content: '在塘朗山附近组织山地野…',
    startTime: '2020-01-24 10:00',
    pusher: '王海青4',
    status: 1,
  },
  {
    icon: require('images/news/new-w.svg'),
    title: '塘朗山网格化搜谱',
    content: '在塘朗山附近组织山地野…',
    startTime: '2020-01-24 10:00',
    pusher: '王海青5',
    status: 1,
  },
  {
    icon: require('images/news/new-w.svg'),
    title: '塘朗山网格化搜谱',
    content: '在塘朗山附近组织山地野…',
    startTime: '2020-01-24 10:00',
    pusher: '王海青6',
    status: 1,
  },
  {
    icon: require('images/news/new-w.svg'),
    title: '塘朗山网格化搜谱',
    content: '在塘朗山附近组织山地野…',
    startTime: '2020-01-24 10:00',
    pusher: '王海青7',
    status: 1,
  },
  {
    icon: require('images/news/new-w.svg'),
    title: '塘朗山网格化搜谱',
    content: '在塘朗山附近组织山地野…',
    startTime: '2020-01-24 10:00',
    pusher: '王海青8',
    status: 0,
  },
];

export const newsListYesTypeData = [
  {
    icon: require('images/news/new-w.svg'),
    title: '塘朗山网格化搜谱',
    content: '在塘朗山附近组织山地野…',
    startTime: '2020-01-24 10:00',
    pusher: '王海青7',
    status: 1,
  },
  {
    icon: require('images/news/new-w.svg'),
    title: '塘朗山网格化搜谱',
    content: '在塘朗山附近组织山地野…',
    startTime: '2020-01-24 10:00',
    pusher: '王海青8',
    status: 1,
  },
];
